# fly.toml app configuration file generated for stock-api on 2025-12-02T17:38:52+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stock-api'
primary_region = 'lax'

[build]
  dockerfile = './Dockerfile'
  dockerignore = './.dockerignore'

[env]
  DEEPSEARCH_API_KEY = ''
  FRED_API_KEY = ''
  GROQ_API_KEY = ''
  MONGO_URI = ''
  NEWS_API_KEY = ''
  NODE_PORT = '8080'
  SERP_API_KEY = ''
  TAVILY_API_KEY = ''

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  ports = [
    { port = 80, handlers = ["http"] },
    { port = 443, handlers = ["tls", "http"] }
  ]

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

[[vm]]
  # Increase VM resources so the runner can unpack large container images
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
